[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
  "forge-std/=lib/forge-std/src/",
  "@chainlink/=lib/chainlink-brownie-contracts/",
  "solady/=lib/solady/src/",
  "halmos-cheatcodes/=lib/halmos-cheatcodes/src/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
